"use client";
import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  ExternalLink,
  Award,
  AlertTriangle,
  Newspaper,
  Calendar,
  Globe,
  Brain,
  Download,
  Share2,
  GraduationCap,
  MessageSquare,
  BookOpen,
} from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";

interface CaseStudyData {
  journalist_name: string;
  case_study_analysis: string;
  journalist_image?: string;
  generation_timestamp: string;
  data_sources_count: number;
  raw_data: {
    sections: {
      articles?: any[];
      youtube_videos?: any[];
      major_articles?: any[];
      awards?: any[];
      controversies?: any[];
      writing_style?: any[];
      career_background?: any[];
      social_media?: any[];
      interviews?: any[];
      peer_reviews?: any[];
    };
  };
}

export default function JournalistProfile() {
  const { name } = useParams<{ name: string }>();
  const navigate = useNavigate();
  const [caseStudy, setCaseStudy] = useState<CaseStudyData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const loadCaseStudy = async () => {
      if (!name) {
        navigate("/");
        return;
      }

      try {
        setLoading(true);
        
        // Try to get data from sessionStorage
        const storedData = sessionStorage.getItem(`case_study_${name}`);
        if (storedData) {
          setCaseStudy(JSON.parse(storedData));
          setLoading(false);
          return;
        }

        // If not in sessionStorage, show error
        setError("Case study not found. Please generate a new case study from the homepage.");
      } catch (err) {
        console.error("Error loading case study:", err);
        setError("Failed to load case study data.");
      } finally {
        setLoading(false);
      }
    };

    loadCaseStudy();
  }, [name, navigate]);

  const downloadCaseStudy = () => {
    if (!caseStudy) return;
    
    const content = `
JOURNALISM CASE STUDY
${caseStudy.journalist_name.toUpperCase()}
Generated: ${new Date(caseStudy.generation_timestamp).toLocaleString()}
Data Sources: ${caseStudy.data_sources_count}

${'='.repeat(80)}

${caseStudy.case_study_analysis}

${'='.repeat(80)}

Generated by DataHalo EDU - Journalism Case Study Generator
https://datahalo.com
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `case-study-${caseStudy.journalist_name.replace(/\s+/g, "-").toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-primary mx-auto"></div>
          <p className="mt-4 text-muted-foreground">Loading case study...</p>
        </div>
      </div>
    );
  }

  if (error || !caseStudy) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted flex items-center justify-center">
        <div className="text-center max-w-md mx-auto p-8">
          <div className="p-4 bg-destructive/10 border border-destructive/30 rounded-xl mb-4">
            <AlertTriangle className="w-16 h-16 text-destructive mx-auto" />
          </div>
          <h2 className="text-2xl font-bold mb-2">Case Study Not Found</h2>
          <p className="text-muted-foreground mb-6">
            {error || "This case study hasn't been generated yet."}
          </p>
          <button
            onClick={() => navigate("/")}
            className="px-6 py-3 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg font-semibold transition-colors"
          >
            Generate Case Study
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted">
      {/* Header */}
      <header className="sticky top-0 z-50 backdrop-blur-lg bg-card/80 border-b border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
          <button
            onClick={() => {
              navigate('/');
              setTimeout(() => {
                const analyzerElement = document.getElementById('analyzer');
                if (analyzerElement) {
                  analyzerElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
                }
              }, 100);
            }}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-card/50 backdrop-blur-sm border border-border/50 hover:border-primary/50 transition-all duration-300 text-foreground hover:text-primary"
          >
            <ArrowLeft className="w-5 h-5" />
            <span className="font-medium">Back to Generator</span>
          </button>
          <div className="flex items-center gap-2">
            <GraduationCap className="w-6 h-6 text-primary" />
            <h1 className="text-xl font-orbitron font-bold text-primary">
              Case Study
            </h1>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
        {/* Header Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-6 rounded-2xl bg-gradient-to-r from-primary/10 to-blue-500/10 border border-primary/30"
        >
          <div className="flex items-start justify-between mb-4">
            <div className="flex items-center gap-4 flex-1">
              {caseStudy.journalist_image && (
                <img 
                  src={caseStudy.journalist_image} 
                  alt={caseStudy.journalist_name}
                  className="w-24 h-24 rounded-full object-cover border-4 border-primary/30 shadow-lg"
                  onError={(e) => {
                    (e.target as HTMLImageElement).style.display = 'none';
                  }}
                />
              )}
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <GraduationCap className="w-6 h-6 text-primary" />
                  <h2 className="text-3xl font-bold text-primary">
                    {caseStudy.journalist_name}
                  </h2>
                </div>
                <p className="text-sm text-muted-foreground">
                  Comprehensive Educational Case Study for Journalism Students
                </p>
              </div>
            </div>
            <div className="flex gap-2">
              <Button
                onClick={downloadCaseStudy}
                variant="outline"
                size="sm"
                className="gap-2"
              >
                <Download className="w-4 h-4" />
                Download
              </Button>
              <Button
                onClick={() => {
                  if (navigator.share) {
                    navigator.share({
                      title: `Case Study: ${caseStudy.journalist_name}`,
                      text: `Check out this comprehensive journalism case study on ${caseStudy.journalist_name}`,
                    });
                  }
                }}
                variant="outline"
                size="sm"
                className="gap-2"
              >
                <Share2 className="w-4 h-4" />
                Share
              </Button>
            </div>
          </div>

          {/* Metadata */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="p-3 rounded-lg bg-card/50 border border-border/50">
              <div className="flex items-center gap-2 mb-1">
                <Calendar className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">Generated</span>
              </div>
              <p className="text-sm font-semibold">
                {new Date(caseStudy.generation_timestamp).toLocaleDateString()}
              </p>
            </div>
            <div className="p-3 rounded-lg bg-card/50 border border-border/50">
              <div className="flex items-center gap-2 mb-1">
                <Globe className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">Data Sources</span>
              </div>
              <p className="text-sm font-semibold">{caseStudy.data_sources_count} sources</p>
            </div>
            <div className="p-3 rounded-lg bg-card/50 border border-border/50">
              <div className="flex items-center gap-2 mb-1">
                <Newspaper className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">Articles Analyzed</span>
              </div>
              <p className="text-sm font-semibold">
                {caseStudy.raw_data?.sections?.articles?.length || caseStudy.raw_data?.sections?.major_articles?.length || 0}
              </p>
            </div>
            <div className="p-3 rounded-lg bg-card/50 border border-border/50">
              <div className="flex items-center gap-2 mb-1">
                <Brain className="w-4 h-4 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">AI Analysis</span>
              </div>
              <p className="text-sm font-semibold">Comprehensive</p>
            </div>
          </div>
        </motion.div>

        {/* Case Study Content */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="p-6 rounded-2xl bg-card/50 backdrop-blur-md border border-border/50"
        >
          <div className="flex items-center gap-2 mb-4">
            <BookOpen className="w-5 h-5 text-primary" />
            <h3 className="text-xl font-bold">Case Study Analysis</h3>
          </div>
          <div className="prose prose-sm md:prose-base max-w-none dark:prose-invert">
            <div className="whitespace-pre-wrap font-sans leading-relaxed text-foreground">
              {caseStudy.case_study_analysis}
            </div>
          </div>
        </motion.div>

        {/* Source Materials */}
        {caseStudy.raw_data?.sections && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="p-6 rounded-2xl bg-card/50 backdrop-blur-md border border-border/50"
          >
            <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
              <ExternalLink className="w-5 h-5 text-primary" />
              Source Materials & References
            </h3>
            
            <Tabs defaultValue="articles" className="w-full">
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="articles">
                  <Newspaper className="w-4 h-4 mr-2" />
                  Articles
                </TabsTrigger>
                <TabsTrigger value="videos">
                  <MessageSquare className="w-4 h-4 mr-2" />
                  Videos
                </TabsTrigger>
                <TabsTrigger value="awards">
                  <Award className="w-4 h-4 mr-2" />
                  Awards
                </TabsTrigger>
              </TabsList>

              <TabsContent value="articles" className="space-y-3 mt-4">
                {(caseStudy.raw_data.sections.articles || caseStudy.raw_data.sections.major_articles) && 
                 (caseStudy.raw_data.sections.articles?.length > 0 || caseStudy.raw_data.sections.major_articles?.length > 0) ? (
                  (caseStudy.raw_data.sections.articles || caseStudy.raw_data.sections.major_articles).map((article: any, idx: number) => (
                    <a
                      key={idx}
                      href={article.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block p-4 rounded-lg bg-muted/30 hover:bg-muted/50 border border-border/50 hover:border-primary/50 transition-all group"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1">
                          <h4 className="font-semibold group-hover:text-primary transition-colors mb-1">
                            {article.title}
                          </h4>
                          <p className="text-xs text-muted-foreground">
                            {article.domain} • {article.word_count} words
                            {article.date && ` • ${article.date}`}
                          </p>
                          {article.snippet && (
                            <p className="text-sm text-muted-foreground mt-2">
                              {article.snippet}
                            </p>
                          )}
                        </div>
                        <ExternalLink className="w-4 h-4 text-muted-foreground group-hover:text-primary flex-shrink-0 mt-1" />
                      </div>
                    </a>
                  ))
                ) : (
                  <p className="text-sm text-muted-foreground p-4">No articles found in this case study.</p>
                )}
              </TabsContent>

              <TabsContent value="awards" className="space-y-3 mt-4">
                {caseStudy.raw_data.sections.awards && caseStudy.raw_data.sections.awards.length > 0 ? (
                  caseStudy.raw_data.sections.awards.map((award: any, idx: number) => (
                    <a
                      key={idx}
                      href={award.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block p-4 rounded-lg bg-muted/30 hover:bg-muted/50 border border-border/50 hover:border-primary/50 transition-all group"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1">
                          <h4 className="font-semibold group-hover:text-primary transition-colors mb-1 flex items-center gap-2">
                            <Award className="w-4 h-4 text-yellow-500" />
                            {award.title}
                          </h4>
                          <p className="text-sm text-muted-foreground mt-2">
                            {award.snippet}
                          </p>
                        </div>
                        <ExternalLink className="w-4 h-4 text-muted-foreground group-hover:text-primary flex-shrink-0 mt-1" />
                      </div>
                    </a>
                  ))
                ) : (
                  <p className="text-sm text-muted-foreground p-4">No awards information found in this case study.</p>
                )}
              </TabsContent>

              <TabsContent value="controversies" className="space-y-3 mt-4">
                {caseStudy.raw_data.sections.controversies && caseStudy.raw_data.sections.controversies.length > 0 ? (
                  caseStudy.raw_data.sections.controversies.map((controversy: any, idx: number) => (
                    <a
                      key={idx}
                      href={controversy.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block p-4 rounded-lg bg-orange-500/5 hover:bg-orange-500/10 border border-orange-500/30 hover:border-orange-500/50 transition-all group"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1">
                          <h4 className="font-semibold group-hover:text-primary transition-colors mb-1 flex items-center gap-2">
                            <AlertTriangle className="w-4 h-4 text-orange-500" />
                            {controversy.title}
                          </h4>
                          <p className="text-sm text-muted-foreground mt-2">
                            {controversy.snippet}
                          </p>
                        </div>
                        <ExternalLink className="w-4 h-4 text-muted-foreground group-hover:text-primary flex-shrink-0 mt-1" />
                      </div>
                    </a>
                  ))
                ) : (
                  <p className="text-sm text-muted-foreground p-4">No controversies found in this case study.</p>
                )}
              </TabsContent>

              <TabsContent value="videos" className="space-y-3 mt-4">
                {caseStudy.raw_data.sections.youtube_videos && caseStudy.raw_data.sections.youtube_videos.length > 0 ? (
                  caseStudy.raw_data.sections.youtube_videos.map((video: any, idx: number) => (
                    <a
                      key={idx}
                      href={video.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block p-4 rounded-lg bg-muted/30 hover:bg-muted/50 border border-border/50 hover:border-primary/50 transition-all group"
                    >
                      <div className="flex items-start gap-3">
                        {video.thumbnail && (
                          <img 
                            src={video.thumbnail} 
                            alt={video.title}
                            className="w-32 h-20 rounded-lg object-cover flex-shrink-0"
                          />
                        )}
                        <div className="flex-1 min-w-0">
                          <h4 className="font-semibold group-hover:text-primary transition-colors mb-1 flex items-center gap-2">
                            <MessageSquare className="w-4 h-4 text-red-500" />
                            {video.title}
                          </h4>
                          <p className="text-xs text-muted-foreground mb-2">
                            {video.channel} • YouTube
                          </p>
                          {video.description && (
                            <p className="text-sm text-muted-foreground line-clamp-2">
                              {video.description}
                            </p>
                          )}
                        </div>
                        <ExternalLink className="w-4 h-4 text-muted-foreground group-hover:text-primary flex-shrink-0 mt-1" />
                      </div>
                    </a>
                  ))
                ) : (
                  <p className="text-sm text-muted-foreground p-4">No YouTube videos found in this case study.</p>
                )}
              </TabsContent>
            </Tabs>
          </motion.div>
        )}

        {/* Educational Footer */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="p-4 rounded-xl bg-primary/5 border border-primary/20"
        >
          <div className="flex items-start gap-2">
            <GraduationCap className="w-4 h-4 text-primary mt-0.5 flex-shrink-0" />
            <div className="text-xs text-muted-foreground">
              <p className="font-semibold text-primary mb-1">Educational Use</p>
              <p>
                This case study is designed for journalism students and educators. Use it for class
                discussions, assignments, research projects, and self-study. Download, print, or share
                with your class. Generate new case studies for different journalists to build a
                comprehensive library of learning materials.
              </p>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
